Models/Appointment.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Health_Care_V1._2.Models
{
    public partial class Appointment
    {
        public decimal Id { get; set; }
        public decimal? PatientId { get; set; }
        public decimal? DoctorId { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Status { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Employee Doctor { get; set; }
        public virtual Account Patient { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

Controllers/PatientDashboardController.cs
using Health_Care_V1._2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Health_Care_V1._2.Controllers
{
    static class Reservation
    {
        public static Appointment NewAppointment { get; set; }
    }

    public class PatientDashboardController : Controller
    {
        private ModelContext _context;

        public PatientDashboardController(ModelContext context)
        {
            _context = context;
        }

        public IActionResult Appointments(decimal accountId)
        {
            #region ViewBagElements
            ViewBag.mainTable = (from record in _context.Mains select record).ToList().FirstOrDefault();
            ViewBag.Fname = HttpContext.Session.GetString("Fname");
            ViewBag.LName = HttpContext.Session.GetString("Lname");
            ViewBag.AccountId = HttpContext.Session.GetInt32("AccountId");
            ViewBag.AppointmentsLinkStatus = "nav-item active";
            ViewBag.invoicesData = _context.Invoices.ToList();
            #endregion ViewBagElements

            #region AppointmentsJoinQuery
            var query = (from app in _context.Appointments
                     where app.PatientId == HttpContext.Session.GetInt32("AccountId")
                     join patAcc in _context.Accounts
                     on app.PatientId equals patAcc.Id
                     join doc in _context.Employees
                     on app.DoctorId equals doc.Id
                     join docAcc in _context.Accounts
                     on doc.AccountId equals docAcc.Id
                     join cli in _context.Clinics
                     on doc.ClinicId equals cli.Id
                     select new AppointemtJoin
                     {
                         //Appointment Inf
                         Id = app.Id,
                         FromDate = app.FromDate,
                         ToDate = app.ToDate,
                         Status = app.Status,

                         //Patient Inf
                         PatientAccountId = patAcc.Id,
                         PatientFname = patAcc.Fname,
                         PatientLname = patAcc.Lname,
                         PatientEmail = patAcc.Email,
                         PatientGender = patAcc.Gender,
                         PatientBoD = patAcc.Bod,

                         //Doctor Inf
                         DoctorId = doc.Id,
                         DoctorFname = docAcc.Fname,
                         DoctorLname = docAcc.Lname,
                         DoctorEmail = docAcc.Email,
                         DoctorProfilePicture = docAcc.ProfilePicture,

                         //Clinic Inf
                         ClinicName = cli.ClinicName,
                         ClinicId = cli.Id
                     });
            #endregion AppointmentsJoinQuery

            return View(query);
        }
        public IActionResult Details(decimal? id)
        {
            #region ViewBagElements
            ViewBag.mainTable = (from record in _context.Mains select record).ToList().FirstOrDefault();
            ViewBag.Fname = HttpContext.Session.GetString("Fname");
            ViewBag.LName = HttpContext.Session.GetString("Lname");
            ViewBag.AccountId = HttpContext.Session.GetInt32("AccountId");
            ViewBag.AppointmentsLinkStatus = "nav-item active";
            #endregion ViewBagElements

            #region AppointmentsJoinQuery
            var query = (from app in _context.Appointments
                         where app.Id == id
                         join patAcc in _context.Accounts
                         on app.PatientId equals patAcc.Id
                         join doc in _context.Employees
                         on app.DoctorId equals doc.Id
                         join docAcc in _context.Accounts
                         on doc.AccountId equals docAcc.Id
                         join cli in _context.Clinics
                         on doc.ClinicId equals cli.Id
                         select new AppointemtJoin
                         {
                             //Appointment Inf
                             Id = app.Id,
                             FromDate = app.FromDate,
                             ToDate = app.ToDate,
                             CreationDate = app.CreationDate,
                             Status = app.Status,

                             //Patient Inf
                             PatientAccountId = patAcc.Id,

                             //Doctor Inf
                             DoctorFname = docAcc.Fname,
                             DoctorMname = docAcc.Mname,
                             DoctorLname = docAcc.Lname,
                             DoctorEmail = docAcc.Email,
                             DoctorProfilePicture = docAcc.ProfilePicture,

                             //Clinic Inf
                             ClinicName = cli.ClinicName,
                             ClinicLogo = cli.ClinicLogo
                         }).FirstOrDefault();
            #endregion AppointmentsJoinQuery

            if (id == null)
            {
                return NotFound();
            }

            if (query == null)
            {
                return NotFound();
            }

            return View(query);
        }

        [HttpGet]
        public IActionResult Create(decimal patientId, string appointmentErrorMsg=null)
        {
            #region ViewBagElements
            ViewBag.mainTable = (from record in _context.Mains select record).ToList().FirstOrDefault();
            ViewBag.Fname = HttpContext.Session.GetString("Fname");
            ViewBag.LName = HttpContext.Session.GetString("Lname");
            ViewBag.AccountId = HttpContext.Session.GetInt32("AccountId");
            ViewBag.AppointmentsLinkStatus = "nav-item active";
            ViewBag.AppointmentExists = appointmentErrorMsg;
            #endregion ViewBagElements

            #region DoctorsSelectListQuery
            ViewData["DoctorId1"] =
                new SelectList(from acc in _context.Accounts
                                join emp in _context.Employees
                                on acc.Id equals emp.AccountId
                                join cli in _context.Clinics
                                on emp.ClinicId equals cli.Id
                                where acc.Permission == "DOCTOR"
                                select new
                                {
                                    AccountId = acc.Id,
                                    FullName = acc.Fname + " " + acc.Mname + " " + acc.Lname,
                                    DoctorId = emp.Id,
                                    ClinicId = cli.Id,
                                    ClinicName = cli.ClinicName
                                },
                "DoctorId",
                "FullName");
            #endregion DoctorsSelectListQuery

            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("Id", "PatientId", "DoctorId", "FromDate", "ToDate", "Status", "CreationDate")] Appointment appointment)
        {
            #region ViewBagElements
            ViewBag.mainTable = (from record in _context.Mains select record).ToList().FirstOrDefault();
            ViewBag.Fname = HttpContext.Session.GetString("Fname");
            ViewBag.LName = HttpContext.Session.GetString("Lname");
            ViewBag.AccountId = HttpContext.Session.GetInt32("AccountId");
            ViewBag.AppointmentsLinkStatus = "nav-item active";
            #endregion ViewBagElements

            if (appointment.FromDate.Minute > 55)
                appointment.FromDate = appointment.FromDate.AddMinutes(-appointment.FromDate.Minute).AddHours(1);
            else
                appointment.FromDate = appointment.FromDate.AddMinutes(-appointment.FromDate.Minute);

            appointment.ToDate = appointment.FromDate.AddMinutes(55);
            appointment.Status = "Waiting";
            appointment.CreationDate = DateTime.Now;
            appointment.PatientId = ViewBag.AccountId;

            if (IsDateAvailable(appointment.FromDate, appointment.DoctorId))
            {
                string appointmentErrorMsg = "There is appointment in this date please choose another date";
                return RedirectToAction("Create", new { patientId = ViewBag.AccountId, appointmentErrorMsg = appointmentErrorMsg });
            }
            if (IsDateDuplicate(appointment.FromDate, appointment.PatientId))
            {
                string appointmentErrorMsg = "You have an appointment in the same date";
                return RedirectToAction("Create", new { patientId = ViewBag.AccountId, appointmentErrorMsg = appointmentErrorMsg });
            }

            try
            {
                if (ModelState.IsValid)
                {
                    ViewBag.Confirmed = true;

                    #region ClinicNameQuery
                    ViewBag.ClinicName = (from doc in _context.Employees
                                          join cli in _context.Clinics
                                          on doc.ClinicId equals cli.Id
                                          select cli.ClinicName).FirstOrDefault();
                    #endregion ClinicNameQuery

                    #region DoctorNameQuery
                    ViewBag.DoctorName = (from doc in _context.Employees
                                          join acc in _context.Accounts
                                          on doc.AccountId equals acc.Id
                                          select new
                                          {
                                              FullName = acc.Fname + " " + acc.Lname
                                          }).FirstOrDefault();

Views/PatientDashboard/Appointments.cshtml
@model IEnumerable<Health_Care_V1._2.Models.AppointemtJoin>

@{
    Layout = "~/Views/Shared/_PatientDashboardLayout.cshtml";
}


<h1 class="view-header">Appointments</h1>

<p>
    <a asp-action="Create" asp-route-patientId="@ViewBag.AccountId">Reserve a New Appointment &plusmn;</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                From Date
            </th>
            <th>
                To Date
            </th>
            <th>
                Status
            </th>
            <th>
                Doctor Name
            </th>
            <th>
                Doctor Email
            </th>
            <th>
                Clinic Name
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            if (item.ToDate <= DateTime.Now && item.Status == "Waiting")
            {
                @Html.ActionLink("", "SetAppointment", "PatientDashboard", new { id = item.Id, status="Cancelled"}, new { @class="clicked" } )
                continue;
            }
            if (item.ToDate <= DateTime.Now && item.Status == "Accepted")
            {
                @Html.ActionLink("", "SetAppointment", "PatientDashboard", new { id = item.Id, status="Completed"}, new { @class="clicked" } )
                continue;
            }
            <tr>
            <td>
                @Math.Round(item.Id, 0)
            </td>
            <td>
                @item.FromDate
            </td>
            <td>
                @item.ToDate
            </td>
            <td>
                @{
                    string circleColor = "#000000";
                    switch (item.Status)
                    {
                        case "Waiting":
                            circleColor = "#FFD133";
                            break;

                        case "Accepted":
                            circleColor = "#1E7F04";
                            break;

                        case "Completed":
                            circleColor = "#63b322";
                            break;

                        case "Rejected":
                            circleColor = "#C80D0D";
                            break;

                        case "Cancelled":
                            circleColor = "#000000";
                            break;
                    }
                }
                        
                <span style="color: @circleColor;">&#9679;</span>
                @item.Status
            </td>
            <td>
                @item.DoctorFname @item.DoctorLname
            </td>
            <td>
                @item.DoctorEmail
            </td>
            <td>
                @item.ClinicName
            </td>
            <td>
               <a asp-action="Details" asp-route-id="@item.Id">
                   <img src="~/images/details.png" alt="Details" title="Details" width="22" height="22" />
               </a> 
               @if (item.Status == "Waiting")
               {
                   <span>|</span>

                   <!-- Cancel Appoitnment -->
                  <a asp-action="SetAppointment" asp-route-id="@item.Id" asp-route-status="Cancelled"
                            title="Cancel Appointment" style="color: red;">
                       &#x2716;
                  </a>
               }
                    @if (item.Status == "Completed")
                    {
                        List<Invoice> invoicesData = ViewBag.invoicesData;
                        Invoice invoice = (from inv in invoicesData
                                 where inv.AppointmentId == item.Id
                                 select inv).FirstOrDefault();
                        <span>|</span>
                        if (!(invoice is null))
                        {
                            <!-- Invoice -->
                            <a asp-action="InvoiceDetails" asp-route-invoiceId=@invoice.Id asp-route-appointmentId="@item.Id" asp-route-clinicId="@item.ClinicId"
                                    asp-route-doctorName="@item.DoctorFname @item.DoctorLname" asp-route-patientId="@item.PatientAccountId" >
                                <img src="~/images/create-invoice.png" title="View Invoice" alt="View Invoice" width="22" height="22" />
                            </a>
                        }
                        else
                        {
                            <!-- Disabled Invoice -->
                            <img src="~/images/disabled-invoice.png" title="Invoice is not ready yet" alt="Invoice is not ready yet" width="22" height="22" />
                        }
                    }
                </td>
        </tr>
}
    </tbody>
</table>

<script>
    const collection = document.getElementsByClassName("clicked");
    for (let i=0; i<collection.length; i++){
        collection[i].click();
    }
</script>

Views/PatientDashboard/Create.cshtml
@model Health_Care_V1._2.Models.Appointment

@{
    Layout = "~/Views/Shared/_PatientDashboardLayout.cshtml";
}

<h1 class="view-header">Reserve a New Appointment</h1>

<h6>Appointment</h6>
<hr />
<div class="row justify-content-between">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Doctor Name</label>
                <select asp-for="DoctorId" class ="form-control" asp-items="ViewBag.DoctorId1" required></select>
            </div>
            <div class="form-group">
                <label asp-for="FromDate" class="control-label"></label>
                @{
                    DateTime minDateTime = DateTime.Now;
                    string minValue = $"{minDateTime.Year}-";

                    minValue += (minDateTime.Month < 10) ? $"0{minDateTime.Month}-" : $"{minDateTime.Month}-";
                    minValue += (minDateTime.Day < 10) ? $"0{minDateTime.Day}T" : $"{minDateTime.Day}T";
                    minValue += (minDateTime.Hour < 10) ? $"0{minDateTime.Hour}:" : $"{ minDateTime.Hour}:";
                    minValue += (minDateTime.Minute < 10) ? $"0{minDateTime.Minute}" : $"{ minDateTime.Minute}";

                    DateTime maxDateTime = minDateTime.AddMonths(5);
                    string maxValue = $"{minDateTime.Year}-";

                    maxValue += (maxDateTime.Month < 10) ? $"0{maxDateTime.Month}-" :  $"{maxDateTime.Month}-";
                    maxValue += (maxDateTime.Day < 10) ? $"0{maxDateTime.Day}T" : $"{maxDateTime.Day}T";
                    maxValue += (maxDateTime.Hour < 10) ? $"0{maxDateTime.Hour}:" : $"{ maxDateTime.Hour}:";
                    maxValue += (maxDateTime.Minute < 10) ? $"0{maxDateTime.Minute}" : $"{ maxDateTime.Minute}";
                }
                <input asp-for="FromDate" class="form-control" required
                    value="@minValue" min="@minValue" max="@maxValue" id="fromDate" />
                <span class="text-danger">@ViewBag.AppointmentExists</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>

    @if (!(ViewBag.Confirmed is null))
    {
        <div class="col-md-5 appointment-confirmed-container">

        <h2 style="text-transform: uppercase; margin-bottom: 35px;">Confirmed Appointment</h2>

        <div class="container bcontent">
            <dl class="row">
                <!-- Clinic Name -->
                <dt class="col-sm-3">Clinic Name</dt>
                <dd class="col-sm-9">@ViewBag.ClinicName</dd>

                <!-- Doctor Name -->
                <dt class="col-sm-3">Doctor Name</dt>
                <dd class="col-sm-9">@ViewBag.DoctorName</dd>

                <!-- From -->
                <dt class="col-sm-3">From</dt>
                <dd class="col-sm-9">@ViewBag.FromDate</dd>

                <!-- To -->
                <dt class="col-sm-3 text-truncate">To</dt>
                <dd class="col-sm-9">@ViewBag.ToDate</dd>
            </dl>

            <div class="justify-content-center row">
                <button onclick="location.href='@Url.Action("AppointmentConfirmed")'" 
                    type="button" class="btn btn-success">Confirmed</button>
            </div>
        </div>
    </div>
    }

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/PatientDashboard/Details.cshtml
@model Health_Care_V1._2.Models.AppointemtJoin

@{
    Layout = "~/Views/Shared/_DoctorDashboardLayout.cshtml";
}

<h1 class="view-header">Details</h1>

<div>
    <h6>Appointment</h6>
    <hr />
    
    <div style="margin-left: 10px; margin-right: 10px; margin-bottom: 25px;">
        <!-- Appointment Information -->
        <table class="table-responsive col-md-12">
            <!-- Caption -->
            <caption>Appointment Information</caption>

            <!-- Headers -->
            <thead>
                <tr>
                    <th>ID</th>
                    <th>From Date</th>
                    <th>To Date</th>
                    <th>Status</th>
                    <th>Creation Date</th>
                </tr>
            </thead>

            <!-- Data -->
            <tbody>
                 <tr>
                     <td>
                         @Model.Id
                     </td>
                     <td>
                         @Model.FromDate
                     </td>
                     <td>
                         @Model.ToDate
                     </td>
                     <td>
                        @{
                            string circleColor = "#000000";
                            switch (@Model.Status)
                            {
                                case "Waiting":
                                    circleColor = "#FFD133";
                                    break;

                                case "Accepted":
                                    circleColor = "#1E7F04";
                                    break;

                                case "Completed":
                                    circleColor = "#ffffff";
                                    break;

                                case "Rejected":
                                    circleColor = "#C80D0D";
                                    break;

                                case "Cancelled":
                                    circleColor = "#000000";
                                    break;
                            }
                        }
                        
                        <span style="color: @circleColor;">&#9679;</span>
                         @Model.Status
                     </td>
                     <td>
                         @Model.CreationDate
                     </td>
                </tr>
            </tbody>
        </table>
        <hr>

        <!-- Doctor Information -->
        <table class="table-responsive col-md-12">
            <!-- Caption -->
            <caption>Doctor Information</caption>

            <!-- Headers -->
            <thead>
                <tr>
                    <th>Doctor Name</th>
                    <th>Doctor Email</th>
                    <th>Profile Picture</th>
                </tr>
            </thead>

            <!-- Data -->
            <tbody>
                <tr>
                    <td>
                        @Model.DoctorFname @Model.DoctorMname @Model.DoctorLname
                    </td>
                    <td>
                        @Model.DoctorEmail
                    </td>
                    <td>
                        <img src="~/images/profile-pictures/@Model.DoctorProfilePicture" alt="Doctor Profile Picture" width="64" height="64" />
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Clinic Information -->
        <table class="table-responsive col-md-12">
            <!-- Caption -->
            <caption>Clinic Information</caption>

            <!-- Headers -->
            <thead>
                <tr>
                    <th>Clinic Name</th>
                    <th>Clinic Logo </th>
                </tr>
            </thead>

            <!-- Data -->
            <tbody>
                <tr>
                    <td>
                        @Model.ClinicName
                    </td>
                    <td>
                        <img src="~/images/clinics-logo/@Model.ClinicLogo" alt="Clinic Logo" width="64" height="64" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
<div>
    <a asp-action="Appointments" asp-route-accountId="@Model.PatientAccountId">Back to List</a>
</div>

Views/PatientDashboard/InvoiceDetails.cshtml
@model IEnumerable<Health_Care_V1._2.Models.InvoiceItem>

@{
    Layout = "~/Views/Shared/_PatientDashboardLayout.cshtml";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.js" integrity="sha512-vNrhFyg0jANLJzCuvgtlfTuPR21gf5Uq1uuSs/EcBfVOz6oAHmjqfyPoB5rc9iWGSnVE41iuQU4jmpXMyhBrsw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<div style="margin: 50px;" id="invoice">
    <div class="row">

        <!-- Logo -->
        <div class="col-md-2 justify-content-center d-flex">
            <img src="~/images/@ViewBag.MainTable.LogoPath" />
        </div>

        <div class="col-md-10 d-flex flex-wrap" id="cli">

            <!-- Clinic Information -->
            <div class="col-md-6">
                <ul class="lll-1">
                    <!-- Clinic Name -->
                    <li>
                        <h3 style="font-weight: bold; font-family: Verdana, Geneva, Tahoma, sans-serif;">
                            @ViewBag.Clinic.ClinicName
                        </h3>
                    </li>
                
                    <!-- Clinic Addresses -->

                    @if (!(ViewBag.ClinicAddresses is null))
                    {
                        @foreach (var item in ViewBag.ClinicAddresses)
                        {
                            <li>
                                @item.Country, @item.City, @item.Street
                                @if(!(item.BuildingNumber is null))
                                {
                                    @item.BuildingNumber
                                }

                            </li>
                        }
                    }

                    <!-- Clinic Phone Number -->
                    @if (!(ViewBag.ClinicPhoneNumber is null))
                    {
                        <li>@ViewBag.ClinicPhoneNumber.PhoneNumber</li>
                    }
                </ul>
            </div>

            <!-- Invoice Information -->
            <div class="col-md-6 d-flex justify-content-end align-items-center">
                <ul class="lll-1">

                    <!-- Invoice Creation Date -->
                    <li>
                        Date: @ViewBag.Invoice.CreationDate.Date
                    </li>
                    
                    <!-- Invoice id -->
                    <li>
                        Invoice ID: <bold>@ViewBag.Invoice.Id</bold>
                    </li>
                </ul>
                
            </div>

        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6 justify-content-start">
            <ul class="lll-2">
                <li>Patient Name</li>
                <li>Age</li>
                @if (!(@ViewBag.PatientAddress is null))
                {
                    <li>Patient Address</li>
                }

                @if (!(@ViewBag.PatientPhoneNumber is null))
                {
                    <li>Patient Phone Number</li>
                }
                
                <li>Patient Email</li>
            </ul>
        </div>

        <div class="col-md-6 justify-content-end">
            <ul class="lll-2">
                
                <!-- Patient Full Name -->
                <li>@ViewBag.Patient.Fname @ViewBag.Patient.Mname @ViewBag.Patient.Lname</li>

                <!-- Patient Age -->
                <li>
                    @{
                        var age = DateTime.Now.Year - ViewBag.Patient.Bod.Year;
                    }
                    @age
                </li>

                <!-- Patient Address -->
                @if (!(@ViewBag.PatientAddress is null))
                {
                    <li>
                        @ViewBag.PatientAddress.Country
                        @if (!(ViewBag.PatientAddress.City is null))
                        {
                            <span>, </span>
                            @ViewBag.PatientAddress.City
                        }
                    </li>
                }

                @if (!(@ViewBag.PatientPhoneNumber is null))
                {
                    <li>@ViewBag.PatientPhoneNumber</li>
                }

                <!-- Patient Email -->
                <li>@ViewBag.Patient.Email</li>
            </ul>
        </div>
    </div>
    <hr />

    <table class="table-responsive" style="width: 100%;" id="example">
        <thead class="inv-thead">
            <tr>
                <th>ID</th>
                <th>Item Name</th>
                <th>Item Description</th>
                <th>Item Quantity</th>
                <th>Item Price</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in @Model)
            {
                <tr>
                    <!-- ID -->
                    <td>@item.Id</td>

                    <!-- Item Name -->
                    <td>@item.ItemName</td>

                    <!-- Item Description -->
                    <td>@item.ItemDescription</td>

                    <!-- Item Quantity -->
                    <td>@item.Quantity</td>

                    <!-- Item Price -->
                    <td>@item.Price</td>
                </tr>
            }

            <tr>
                <td colspan="4" style="font-size:2rem; font-weight:bold; letter-spacing: 3px;">
                    Total
                </td>
                <td style="font-size:2rem; font-weight:bold;">
                    @ViewBag.TotalPrice
                </td>
            </tr>
        </tbody>
    </table>

    <div class="row" style="margin: 50px;">

        <div class="col-md-6">
            <h6>Doctor Note:</h6>
            <!-- Note Textarea -->
            <textarea class="invoice-note col-md-11" disabled >@ViewBag.Invoice.Notes</textarea>
        </div>

        <div class="col-md-6 d-flex justify-content-end flex-column">
            @if (@ViewBag.Invoice.Status == "UNPAID")
            {
                <!-- Pay -->
                <div class="row justify-content-end align-items-center" style="margin-bottom: 15px;">
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("Rate", "PatientDashboard", new {invoiceId=@ViewBag.Invoice.Id})'">Pay</button>
                </div>                
            }

            <!-- Download -->
            <div class="row justify-content-end">
                <button class="btn btn-dark" id="download" >Download</button>
            </div>
            
        </div>
    </div>

    <hr />
    <div class="row justify-content-center">
        <h6>Thank you</h6>
    </div>
    <hr />
</div>

<script src="~/dashboard/assets/js/pdf-invoice.js"></script>

Views/PatientDashboard/Rate.cshtml
@model Health_Care_V1._2.Models.Invoice

@{
    Layout = "~/Views/Shared/_PatientDashboardLayout.cshtml";
}

<h1 class="view-header">Rate Our Services</h1>

<div class="row justify-content-around" style="margin: 50px; padding: 50px;">
    <div class="col-md-4">
        <div class="doc-profile-pic-container" >
            <img src="~/images/clinics-logo/@ViewBag.Clinic.ClinicLogo" alt="@ViewBag.Clinic.ClinicName Logo"
                class="img-fluid doc-profile-pic-" width=150 height=150 />
        </div>

        <h5 class="d-flex justify-content-center" >@ViewBag.Clinic.ClinicName</h5>
        <input class="d-block" style="margin:auto;" type="number" name="clinicRate" min=1 max=5 />
    </div>

    <div class="col-md-4">
        <div class="doc-profile-pic-container" >
            <img src="~/images/profile-pictures/@ViewBag.Doctor.ProfilePicture" alt="@ViewBag.Doctor.ProfilePicture Profile Picture"
                class="img-fluid doc-profile-pic-" width=150 height=150 />
        </div>

        <h5 class="d-flex justify-content-center">@ViewBag.Doctor.FullName</h5>
        <input class="d-block" style="margin:auto;" type="number" name="doctorRate" min=1 max=5 />
    </div>

    <div 
</div>